import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/creditdebitcardpayments">CreditDebitCardPayments</Link>
        </li>
        <li>
          <Link to="/mapsettings">MapSettings</Link>
        </li>
        <li>
          <Link to="/expressdelivery">ExpressDelivery</Link>
        </li>
        <li>
          <Link to="/payments">Payments</Link>
        </li>
        <li>
          <Link to="/requestmanagement">RequestManagement</Link>
        </li>
        <li>
          <Link to="/summarycard">Summarycard</Link>
        </li>
        <li>
          <Link to="/shippingaddressvalidation">ShippingAddressValidation</Link>
        </li>
        <li>
          <Link to="/shippingchargecalculator">ShippingChargeCalculator</Link>
        </li>
        <li>
          <Link to="/geofence">Geofence</Link>
        </li>
        <li>
          <Link to="/location">Location</Link>
        </li>
        <li>
          <Link to="/zipcodesearch">ZIPCodeSearch</Link>
        </li>
        <li>
          <Link to="/landingpage">LandingPage</Link>
        </li>
        <li>
          <Link to="/paypalintegration">PaypalIntegration</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
